"""Add working_hours, rating, has_online_booking, duration_days

Revision ID: 66762e1956c6
Revises: bcb99b7fa886
Create Date: 2026-06-27 15:50:28.557602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66762e1956c6'
down_revision: Union[str, None] = 'bcb99b7fa886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('working_hours', sa.String(length=255), nullable=True))
    op.add_column('clinics', sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('clinics', sa.Column('has_online_booking', sa.Boolean(), nullable=False))
    op.add_column('prices', sa.Column('duration_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'duration_days')
    op.drop_column('clinics', 'has_online_booking')
    op.drop_column('clinics', 'rating')
    op.drop_column('clinics', 'working_hours')
    # ### end Alembic commands ###
