"""Init

Revision ID: bcb99b7fa886
Revises: 
Create Date: 2026-06-26 20:34:04.987484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb99b7fa886'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clinics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_clinics_city', 'clinics', ['city'], unique=False)
    op.create_index('idx_clinics_name', 'clinics', ['name'], unique=False)
    op.create_table('source_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('processed_records', sa.Integer(), nullable=True),
    sa.Column('created_records', sa.Integer(), nullable=True),
    sa.Column('updated_records', sa.Integer(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=True),
    sa.Column('raw_service_name', sa.String(length=500), nullable=False),
    sa.Column('raw_price', sa.String(length=100), nullable=False),
    sa.Column('cleaned_service_name', sa.String(length=500), nullable=True),
    sa.Column('cleaned_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_index('idx_services_canonical_name', 'services', ['canonical_name'], unique=False)
    op.create_index('idx_services_category_id', 'services', ['category_id'], unique=False)
    op.create_table('needs_review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('suggested_service_id', sa.UUID(), nullable=True),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.CheckConstraint('price >= 0.00', name='chk_positive_price'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prices_clinic_service', 'prices', ['clinic_id', 'service_id'], unique=False)
    op.create_index('idx_prices_live_lookup', 'prices', ['price', 'last_updated'], unique=False)
    op.create_table('service_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_name')
    )
    op.create_index('idx_service_aliases_name', 'service_aliases', ['alias_name'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('price_id', sa.UUID(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_history_lookup', 'price_history', ['price_id', 'changed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_history_lookup', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('idx_service_aliases_name', table_name='service_aliases')
    op.drop_table('service_aliases')
    op.drop_index('idx_prices_live_lookup', table_name='prices')
    op.drop_index('idx_prices_clinic_service', table_name='prices')
    op.drop_table('prices')
    op.drop_table('needs_review')
    op.drop_index('idx_services_category_id', table_name='services')
    op.drop_index('idx_services_canonical_name', table_name='services')
    op.drop_table('services')
    op.drop_table('raw_records')
    op.drop_table('processing_jobs')
    op.drop_table('source_files')
    op.drop_index('idx_clinics_name', table_name='clinics')
    op.drop_index('idx_clinics_city', table_name='clinics')
    op.drop_table('clinics')
    op.drop_table('categories')
    # ### end Alembic commands ###
